[package]
name = "a01_quicksort"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fastrand = "2.0.1"
firedbg-lib = "0.1.2"
structopt = "0.3.26"
